### ISSUE TITLE
Resizing images for web

### ISSUE THREAD

**Issue by ArcCha** [KSIUJ/www.ksi#18]
It might be helpful to include plugins such as:

- [jekyll-responsive-image](https://github.com/wildlyinaccurate/jekyll-responsive-image)
- [jekyll-assets](https://github.com/envygeeks/jekyll-assets)
- [jekyll-compress-images](https://github.com/valerijaspasojevic/jekyll-compress-images)

in order to resolve issues mentioned in recent pull requests (#13 and #14).

**Comment by apardyl** [comment]
done in #23
